
import { Inter } from "next/font/google"
import "../globals.css"
import Header from "@/components/Header"
import { getServerSession } from "next-auth"
import { authOptions } from "../api/auth/[...nextauth]/route"
import { redirect } from "next/navigation"
import Image from "next/image"
import AppSidebar from "@/components/layouts/AppSidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppTemplate({ children, ...rest }) {
  const session = await getServerSession(authOptions)
  if (!session) {
    return redirect('/')
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen">
          <aside className="bg-green w-48 p-4">
            <div className="overflow-hidden w-24 mx-auto">
              <Image 
                className="rounded-full"
                src={session.user.image} 
                alt={`avatar`} 
                width={128} 
                height={128}
              />
            </div>
            <AppSidebar />
          </aside>
          <div className="grow">
            <div className="bg-white m-4 p-4">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
